language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
#  - '7.0'
#  - hhvm
#  - nightly

before_install:
  - phpenv config-rm xdebug.ini
  - phpenv config-add php-test.ini
  - composer self-update
  - composer validate

install:
  - travis_retry composer install --prefer-dist

